<a href="https://colab.research.google.com/github/jaylin0418/2025-IM-Camp/blob/main/python2_notebook_ans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 台大資管營：Python (2)

這是台大資管營的第二堂 Python 程式設計課程講義，希望可以幫助學員進一步了解並掌握 Python 的進階功能。

涵蓋的主題包括：
- 元組 Tuple
- 集合 Set
- 字典 Dictionary
- 函數 Function
- 物件 Object
- 模組與套件

## Tuple

在 Python 中，我們使用 `(小括號)` 表達元組

In [ ]:
a_tuple = tuple()
a_tuple = ()
coordinate = (0, 0)

In [ ]:
coordinate = (0, 0)
print(coordinate) # 印出 (0, 0)
print(coordinate[0])  # 印出 0

(0, 0)
0


tuple 和 list 是非常相似的東西，不過 tuple 在建立之後就無法更改裡面的資料。

所以我們不能對一個 tuple 新增元素、刪除元素。

### 小試身手 (1)

請寫出一段 Python 程式碼，來創建一個元組，並嘗試將其中的元素改為其他值。觀察並說明程式執行的結果。

In [ ]:
# TODO

### 解答

In [ ]:
my_tuple = (1, 2, 3)

try:
    my_tuple[0] = 10
except TypeError as e:
    print("Error:", e)

print("Tuple after attempting modification:", my_tuple)

Error: 'tuple' object does not support item assignment
Tuple after attempting modification: (1, 2, 3)


## Set

在 Python 中，set 是一個裝資料的大容器：

- 同樣的值只出現一次
- 裡面裝的元素之間是沒有位置關係的。

In [ ]:
a_set = set() # 空集合
a_set.add(10) # 添加元素 10
a_set.add(20) # 添加元素 20
a_set.add(10) # 再次添加 10（無效，集合不允許重複）
a_set # ???

{10, 20}

remove 方法從集合中刪除指定的元素。如果該元素不存在，會拋出 `KeyError`。

In [ ]:
a_set = {1, 2, 3, 4}
a_set.remove(3) # 移除元素 3
print(a_set) # {1, 2, 4}
#a_set.remove(5) # Error

{1, 2, 4}


discard 方法從集合中刪除指定的元素。如果該元素不存在，不會拋出錯誤。

In [ ]:
a_set.discard(5) # 沒有錯誤

union 方法用於返回兩個集合的聯集，包含兩個集合所有唯一元素的集合。

In [ ]:
a_set = {1, 2, 3}
b_set = {3, 4, 5}
result = a_set.union(b_set) # 返回兩集合的聯集
print(result) # {1, 2, 3, 4, 5}

{1, 2, 3, 4, 5}


intersection 方法用於返回兩個集合的交集，即同時存在於兩個集合中的元素。

In [ ]:
a_set = {1, 2, 3}
b_set = {3, 4, 5}
result = a_set.intersection(b_set) # 返回兩集合的交集
print(result) # {3}

{3}


### 小試身手 (2)

In [ ]:
basketball_club = {"Alice", "Bob", "Charlie", "David"}
volleyball_club = {"Eve", "Frank", "Charlie", "Alice"}

# 問題 1: 新增 Grace 到籃球社

# 問題 2: 從排球社移除 Eve
print("籃球社成員:", basketball_club)
print("排球社成員:", volleyball_club)

# 問題 3: 同時參加兩個社團的成員
# TODO: both_clubs =
#print("同時參加兩個社團的成員:", both_clubs)

# 問題 4: 至少參加一個社團的成員
# TODO: all_members =
#print("至少參加一個社團的成員:", all_members)

籃球社成員: {'Alice', 'Bob', 'Charlie', 'David'}
排球社成員: {'Charlie', 'Frank', 'Eve', 'Alice'}


### 解答

In [ ]:
basketball_club = {"Alice", "Bob", "Charlie", "David"}
volleyball_club = {"Eve", "Frank", "Charlie", "Alice"}

# 問題 1: 新增 Grace 到籃球社
basketball_club.add("Grace")

# 問題 2: 從排球社移除 Eve
volleyball_club.remove("Eve")

# 問題 3: 同時參加兩個社團的成員
both_clubs = basketball_club.intersection(volleyball_club)
print("同時參加兩個社團的成員:", both_clubs)

# 問題 4: 至少參加一個社團的成員
all_members = basketball_club.union(volleyball_club)
print("至少參加一個社團的成員:", all_members)

# 更新後的名單
print("籃球社成員:", basketball_club)
print("排球社成員:", volleyball_club)


同時參加兩個社團的成員: {'Charlie', 'Alice'}
至少參加一個社團的成員: {'Alice', 'Bob', 'Grace', 'David', 'Charlie', 'Frank'}
籃球社成員: {'Bob', 'Charlie', 'Alice', 'Grace', 'David'}
排球社成員: {'Charlie', 'Frank', 'Alice'}


## Dictionary

字典是由鍵值對（key-value pairs）組成的無序集合。

- 鍵是唯一的，而值可以是任何資料類型。

- 可以通過鍵來存取對應的值。

在 Python 中，我們使用 `{大括號}` 表達字典

In [ ]:
#創建一個空字典：
my_dict = {} # 空字典

In [ ]:
#使用鍵值對初始化字典：
person = {"name": "Alice", "age": 25, "city": "New York"}
print(person) # {'name': 'Alice', 'age': 25, 'city': 'New York'}

{'name': 'Alice', 'age': 25, 'city': 'New York'}


當我們想要取出某個 key 所對應到的 value，我們可以用：`dict[key]`。

In [ ]:
# 例如，如果想要求出 name 這個 key 所對應的 value，我們可以這樣寫：

person['name'] # 程式就會回傳 'Alice'

'Alice'

字典更改和增加的語法一模一樣!

如果我們想要將 age 的值改為 30，可以這樣寫：

In [ ]:
person["age"] = 30 # 更改 age 的值
person["school"] = "NTU"

In [ ]:
person

{'name': 'Alice', 'age': 30, 'city': 'New York', 'school': 'NTU'}

我們有兩種方法可以刪除字典中的元素：

1. 使用 `del` 刪除指定鍵：

In [ ]:
del person["city"] # 刪除 "city" 這個鍵及其對應的值
print(person) # {'name': 'Alice', 'age': 30, 'school': 'NTU'}

{'name': 'Alice', 'age': 30, 'school': 'NTU'}


2. 使用 `pop` 刪除指定鍵：

In [ ]:
age = person.pop("age") # 刪除並返回 "age" 的值
print(person) # {'name': 'Alice', 'school': 'NTU'}
print("Age:", age) # 30

{'name': 'Alice', 'school': 'NTU'}
Age: 30


在某些應用中，我們只想取出字典中的鍵或值：
1. 使用 `keys()` 取出所有鍵：

In [ ]:
keys = person.keys()
print(keys)  # dict_keys(['name', 'school'])

dict_keys(['name', 'school'])


2. 使用 `values` 取出所有值：


In [ ]:
values = person.values()
print(values)  # dict_values(['Alice', 'NTU'])

dict_values(['Alice', 'NTU'])


3. 使用 `items()` 取出所有鍵值對

In [ ]:
items = person.items()
print(items)  # dict_items([('name', 'Alice'), ('school', 'NTU')])

dict_items([('name', 'Alice'), ('school', 'NTU')])


### 小試身手 (3)

(ZeroJudge b523).


題目：有多個輸入被存在 `input_lines`中，每一個元素都是可能包含大小寫英文字母、數字、空白的字串。

對於每一個字串，判斷其是否為第一次出現，若該字串是第一次出現，就印出 NO。若該字串曾經出現過，則印出 YES。

In [ ]:
input_lines = [
    "Hello World",
    "Python is great",
    "Hello World",
    "Hello Python",
    "Python is great",
    "Data Science",
    "Machine Learning",
    "Data Science",
    "Deep Learning",
    "Python is great",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Analysis",
    "Hello Python",
    "Deep Learning"
]

## 請接著往下寫
## TODO

你的程式碼應該印出：

```
NO
NO
YES
NO
YES
NO
NO
YES
NO
YES
NO
YES
NO
YES
YES
```

### 解答

In [ ]:
seen = {}

# 判斷每行是否為第一次出現
for line in input_lines:
    if line not in seen:
        print("NO")
        seen[line] = 1  # 記錄該字串第一次出現
    else:
        print("YES")

NO
NO
YES
NO
YES
NO
NO
YES
NO
YES
NO
YES
NO
YES
YES


## Function

### 函數的基本操作

- 函數定義與呼叫

In [ ]:
'''
def 函數名稱(參數1, 參數2, ...):
    """函數的說明（可選）"""
    函數的邏輯
    return 返回值（可選）

'''

'\ndef 函數名稱(參數1, 參數2, ...):\n    """函數的說明（可選）"""\n    函數的邏輯\n    return 返回值（可選）\n    \n'

In [ ]:
# 定義函數
def greet(name):
    """打招呼函數"""
    return f"Hello, {name}!"

# 呼叫函數
message = greet("Alice")
print(message)  # Hello, Alice!

Hello, Alice!


- 帶有預設參數的函數

In [ ]:
def greet(name="Guest"):
    """打招呼函數，帶預設參數"""
    return f"Hello, {name}!"

# 不傳參數，使用預設值
print(greet()) # Hello, Guest!

# 傳入參數，覆蓋預設值
print(greet("Alice")) # Hello, Alice!

Hello, Guest!
Hello, Alice!


- 帶多個參數的函數

In [ ]:
def weighted_average(a, b, weight_a=0.5, weight_b=0.5):
    """計算兩數的加權平均數"""
    return (a * weight_a) + (b * weight_b)

# 呼叫函數，使用預設權重
print(weighted_average(80, 90))  # 85.0

# 傳入自定義權重
print(weighted_average(80, 90, weight_a=0.7, weight_b=0.3))  # 83.0

85.0
83.0


- 如何將參數傳入函數？

In [ ]:
def intro(name, country, age):
    print("My name is " + name + ". I'm " + str(age) + " years old. I'm from " + country + ".")

- 如果沒有特別指定，傳入參數的順序要依照函數宣告時所使用的順序：

In [ ]:
intro("John", "Taiwan (R.O.C.)", 18)

My name is John. I'm 18 years old. I'm from Taiwan (R.O.C.).


- 我們也可以用關鍵字傳參數，在傳入的值前面「註明」其所對應的參數名稱！

In [ ]:
intro(country = "Taiwan (R.O.C.)", age = 18, name ="John")

My name is John. I'm 18 years old. I'm from Taiwan (R.O.C.).


使用關鍵字參數的範例

In [ ]:
def display_info(**info):
    """顯示輸入的資訊"""
    for key, value in info.items():
        print(f"{key}: {value}")

# 傳入多個鍵值對
display_info(name="Alice", age=25, city="New York")
# 輸出:
# name: Alice
# age: 25
# city: New York

name: Alice
age: 25
city: New York


### 變數範疇與命名空間

In [ ]:
# 全域變數
x = 10 # x 在全域範疇內

def example_function():
    print(x) # 訪問全域變數 x

example_function() # 輸出 10

10


In [ ]:
def example_function():
    # 區域變數
    x = 5 # x 在區域範疇內
    print(x) # 訪問區域變數 x

example_function() # 輸出 5
# print(x) 會引發錯誤，因為 x 是區域變數，無法在函數外部訪問

5


### 小試身手 (4)

In [ ]:
def function_1():
    x = 5  # 區域變數 (local variable)
    print("In function_1, x =", x)

def function_2():
    x = 6  # 區域變數 (local variable)
    print("In function_2, x =", x)

x = 8  # 全域變數 (global variable)
function_1()
function_2()
print("In main, x =", x)


In function_1, x = 5
In function_2, x = 6
In main, x = 8


### 遞迴函數
- 其定義中調用自身的函數。
- 用來解決那些可以分解為相同問題的較小版本的問題。

In [ ]:
def factorial(n):
    if n == 0:
        return 1 # 檢查是否為 base case
    else:
        return n * factorial(n-1) # 如果未達到，則進行遞迴

In [ ]:
print(factorial(5))  # 120

120


### 小試身手 (5)

(ZeroJudge e357).

定義函數 $F(x)$

$$
F(x) =
\begin{cases}
1 & \text{若 } x = 1 \\
F\left(\frac{x}{2}\right) & \text{若 } x \text{ 為偶數} \\
F(x - 1) + F(x + 1) & \text{其餘情況}
\end{cases}
$$

請在講義 Jupyter Notebook 中寫出此函數，並算出 $F(14)$ 和 $F(15)$。

In [ ]:
## 請接著往下寫
def F(x):
    pass
    # TODO

### 解答

In [ ]:
def F(x):
    if x == 1:
        return 1
    elif x % 2 == 0:
        return F(x // 2)
    else:
        return F(x - 1) + F(x + 1)

print(F(14), F(15))

3 4


## Object

將物件類比為一個「盒子」，內部包含：
- **屬性 (Attributes)**：描述物件的資料 (如名稱、顏色)。
- **方法 (Methods)**：操作物件的行為 (如喵喵叫、吃東西)。

---

##### 類別 (Class)
用來定義物件的範疇，規範所有屬性與方法的共同特徵。

例如，定義「貓咪」類別，包含：
- **屬性**：名字、毛色。
- **方法**：喵喵叫、睡覺。

---

##### 實例 (Instance)
具體化的物件，例如：
- **貓咪實例**: 大橘、小白。  
  它們的名字不同，但都屬於「貓咪」類別，共享基本屬性和方法。


In [ ]:
class Cat:
    def __init__(self, name, color, weight):
        self.name = name
        self.color = color
        self.weight = weight
    def meow(self):
        print(f"{self.name} says Meow!")
    def eat(self, food):
        print(f"{self.name} is eating {food}.")
    def sleep(self, hours):
        print(f"{self.name} sleeps for {hours} hours.")

In [ ]:
cat1 = Cat("大橘", "橘色", 5.5)
cat2 = Cat("小白", "白色", 4.2)
cat3 = Cat("黑咪", "黑色", 6.0)

cat1.meow() # 大橘 says Meow!
cat2.eat("魚") # 小白 is eating 魚.
cat3.sleep(10) # 黑咪 sleeps for 10 hours.

大橘 says Meow!
小白 is eating 魚.
黑咪 sleeps for 10 hours.


## 模組與套件

匯入整個模組或套件

`import 模組套件或名稱`

匯入模組或套件，並給別名

`import 模組或套件名稱 as 別名`

匯入模組或套件中特定的函數或類別

`from 模組或套件名稱 import 子模組, 套件或函數名稱`

In [ ]:
import numpy as np

# 在 Numpy 中建立陣列：
arr = np.array([1, 2, 3, 4])
print(arr) # [1 2 3 4]

# 矩陣及向量運算：
result = np.dot([1, 2], [3, 4])
print(result) # 11

# 數學運算：
sin_values = np.sin(arr)
print(sin_values) # [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]

[1 2 3 4]
11
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


### 小試身手 (6)
請完成以下的題目！

在日常的程式開發中，Numpy 是一個強大且常用的數值運算工具，適合用來處理陣列與矩陣運算。本練習的目的是讓你熟悉 Numpy 的基本操作，包含陣列的建立、基本運算、條件篩選以及簡單的矩陣操作。

以下是幾個練習題，請依據提示補上程式碼並完成運算：
1. 建立 Numpy 陣列並進行操作。
2. 使用 Numpy 進行簡單的數學運算。
3. 熟悉矩陣轉置與條件篩選的操作。
4. 嘗試使用隨機數生成並進行基本的統計分析。

請完成程式中的 `TODO` 區塊，並嘗試運行程式檢查結果是否正確！

Hint: 善用各種搜尋工具！

In [ ]:
import numpy as np

# 題目 1: 建立與操作 Numpy 陣列
# 1-1. 建立一個一維陣列 arr1，內容為 [10, 20, 30, 40, 50]，並列印出來。
# TODO: arr1 =

# 1-2. 建立一個二維陣列 arr2，內容為 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]，並列印出來。
# TODO: arr2 =

# 題目 2: 陣列基本運算
# 2-1. 創建兩個陣列 arr1 = np.array([1, 2, 3]) 和 arr2 = np.array([4, 5, 6])，計算它們的逐元素相加。
# TODO: sum_result =

# 2-2. 計算 arr1 與 arr2 的逐元素乘積。
# TODO: product_result =

# 題目 3: 數學運算
# 建立一個陣列 arr = np.array([0, np.pi/2, np.pi])，計算它的 sin 值。
# TODO: sin_values =

# 題目 4: 矩陣運算
# 創建一個矩陣 A，內容為 [[1, 2], [3, 4]]，計算它的轉置 (transpose)。
# TODO: A =
# TODO: transpose_A =

# 題目 5: 條件篩選
# 建立一個陣列 arr = np.array([1, 2, 3, 4, 5, 6])，篩選出所有大於 3 的數字。
# TODO: filtered_arr =

# 附加挑戰
# 請試著用 Numpy 產生 100 個標準常態分布的隨機數，並計算它的平均值。
# TODO: random_numbers =
# TODO: mean =

In [ ]:
import numpy as np

# 題目 1: 建立與操作 Numpy 陣列
# 1-1. 建立一個一維陣列 arr1，內容為 [10, 20, 30, 40, 50]，並列印出來。
arr1 = np.array([10, 20, 30, 40, 50])
print("arr1:", arr1)

# 1-2. 建立一個二維陣列 arr2，內容為 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]，並列印出來。
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("arr2:")
print(arr2)

# 題目 2: 陣列基本運算
# 2-1. 創建兩個陣列 arr1 = np.array([1, 2, 3]) 和 arr2 = np.array([4, 5, 6])，計算它們的逐元素相加。
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_result = arr1 + arr2
print("Sum of arr1 and arr2:", sum_result)

# 2-2. 計算 arr1 與 arr2 的逐元素乘積。
product_result = arr1 * arr2
print("Product of arr1 and arr2:", product_result)

# 題目 3: 數學運算
# 1. 建立一個陣列 arr = np.array([0, np.pi/2, np.pi])，計算它的 sin 值。
arr = np.array([0, np.pi/2, np.pi])
sin_values = np.sin(arr)
print("Sin values of arr:", sin_values)

# 題目 4: 矩陣運算
# 1. 創建一個矩陣 A，內容為 [[1, 2], [3, 4]]，計算它的轉置 (transpose)。
A = np.array([[1, 2], [3, 4]])
transpose_A = A.T
print("Matrix A:")
print(A)
print("Transpose of A:")
print(transpose_A)

# 題目 5: 條件篩選
# 1. 建立一個陣列 arr = np.array([1, 2, 3, 4, 5, 6])，篩選出所有大於 3 的數字。
arr = np.array([1, 2, 3, 4, 5, 6])
filtered_arr = arr[arr > 3]
print("Filtered array (elements > 3):", filtered_arr)

# 附加挑戰
# 請試著用 Numpy 產生 100 個標準常態分布的隨機數，並計算它的平均值。
random_numbers = np.random.randn(100)  # 產生 100 個標準常態分布的數字
mean = np.mean(random_numbers)
print("Random numbers:", random_numbers)
print("Mean of random numbers:", mean)


arr1: [10 20 30 40 50]
arr2:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of arr1 and arr2: [5 7 9]
Product of arr1 and arr2: [ 4 10 18]
Sin values of arr: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Matrix A:
[[1 2]
 [3 4]]
Transpose of A:
[[1 3]
 [2 4]]
Filtered array (elements > 3): [4 5 6]
Random numbers: [ 2.18661173 -0.28953573  2.18129802 -0.51785695  0.19285669  1.93176663
 -0.09857885  0.95791781  0.79934296  0.69313688 -1.15636882  0.88759415
 -1.78596579 -0.34985993  0.48760798  1.09547038  0.16980082  0.23534313
 -1.39637677 -0.65128477  1.3704337  -0.47273644  0.52247674 -0.65290948
 -0.0540018   2.09430002  0.93911079  0.91233466 -0.58369651 -0.18855816
 -0.02371708  0.03468095 -0.42296861 -0.29775316  1.20830777 -0.7664189
  0.2942058  -1.85432507  0.43363231  1.72598284  0.69349037  0.56445267
  0.37967418  0.46154851  1.79592327 -0.05012489  2.52467701  0.86811524
 -0.62638639 -0.69155206  0.79714892  0.62859099  0.42143642  0.74505268
  0.07185307 -0.05973113 -0.15384674 -1.811393